### ISSUE TITLE
Add cors options

### ISSUE THREAD

**Issue by zenoplex** [rymizuki/node-hariko#3]
It would be nice to have cors option for the server.
It seems to be in the code but not exposed as an API.

Perhaps might want to add below in hariko.js?

line:17

``` javascript
cors: argv.cors
```

line:38

``` javascript
cors: this.options.cors
```

**Comment by rymizuki** [comment]
@zenoplex  
It is you're right. Fixed. thanks you!

**Comment by zenoplex** [comment]
Confirmed fix with 1.1.1
Thanks :smile:
